[build]
  publish = "public"
  command = "cd public && hugo --gc --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.51"
  HUGO_THEME = "hugo-serif"
  HUGO_BASEURL = "https://hugo-serif.netlify.com/"